import {} from "./widgets/individual-comission-card"
import {} from "./widgets/workshop-detail"
import {} from "./widgets/workshop-hobbyists-section"
import {} from "./widgets/workshop-masters-section"
import {} from "./widgets/workshop-rooms-section"
